# Generated by Django 5.2.12 on 2026-03-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('app_name', models.CharField(max_length=255)),
                ('install_type', models.CharField(choices=[('FORCE_INSTALLED', 'Force Installed'), ('ALLOWED', 'Allowed'), ('BLOCKED', 'Blocked')], default='ALLOWED', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('sync_status', models.CharField(choices=[('NEVER_SYNCED', 'Never Synced'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='NEVER_SYNCED', max_length=32)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applications', models.ManyToManyField(blank=True, related_name='policies', to='mdm.application')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_status', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='mdm.policy')),
            ],
        ),
    ]
